build:
  version: "1.0"

order-service:
  message: "E-Commerce-App order service production stage APIs"
  contactDetails:
    name: "Mahmut Ali Åžahinkaya - Developer"
    email: "mahmutsahinkaya@gmail.com"
    linkedin: "https://www.linkedin.com/in/mahmutalisahinkaya/"

