build:
  version: "2.0"

reportservice:
  message: "E-Commerce-App report service test stage APIs"
  contactDetails:
    name: "Mahmut Ali Åžahinkaya - Developer"
    email: "mahmutsahinkaya@gmail.com"
    linkedin: "https://www.linkedin.com/in/mahmutalisahinkaya/"

